name: GitHub Actions Demo
run-name: GitHub Actions Demo

# 觸發此 action 的時機
on:
  schedule:
    - cron: "55 12 * * *"  # UTC 每天下午 12:55 執行此 action（等同於台灣晚上 8:55 執行）
  workflow_dispatch:  # 可以手動執行此 action

# 預先定義此 action 要幹嘛
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo '執行成功'
